/*!
 * button-frame.js — GENERATED by tools/build-buttons.js. Do not edit.
 *
 * The buttons cut from assets/source/btn.png and assets/source/new plus-minus.png and assets/source/image.png, and where each one's round end finishes.
 * `cap` is that width in the image's own pixels: draw the left cap at its
 * true proportions, the right cap at its true proportions, and stretch the
 * sliver between them to whatever width the button needs. Stretching the
 * whole picture instead turns the round ends into ovals.
 */
(function (global) {
  'use strict';
  var F = {
    "sun": {
      "src": "assets/ui/btn-sun.webp",
      "w": 285,
      "h": 130,
      "cap": 73
    },
    "tangerine": {
      "src": "assets/ui/btn-tangerine.webp",
      "w": 291,
      "h": 130,
      "cap": 73
    },
    "correct": {
      "src": "assets/ui/btn-correct.webp",
      "w": 283,
      "h": 129,
      "cap": 72
    },
    "wrong": {
      "src": "assets/ui/btn-wrong.webp",
      "w": 285,
      "h": 129,
      "cap": 72
    },
    "convex": {
      "src": "assets/ui/btn-convex.webp",
      "w": 289,
      "h": 131,
      "cap": 73
    },
    "concave": {
      "src": "assets/ui/btn-concave.webp",
      "w": 284,
      "h": 130,
      "cap": 73
    },
    "regular": {
      "src": "assets/ui/btn-regular.webp",
      "w": 285,
      "h": 131,
      "cap": 73
    },
    "irregular": {
      "src": "assets/ui/btn-irregular.webp",
      "w": 286,
      "h": 130,
      "cap": 73
    },
    "sky": {
      "src": "assets/ui/btn-sky.webp",
      "w": 286,
      "h": 130,
      "cap": 73
    },
    "plum": {
      "src": "assets/ui/btn-plum.webp",
      "w": 286,
      "h": 130,
      "cap": 73
    },
    "stepMinus": {
      "src": "assets/ui/btn-stepMinus.webp",
      "w": 258,
      "h": 240,
      "cap": 0,
      "glyph": true
    },
    "stepPlus": {
      "src": "assets/ui/btn-stepPlus.webp",
      "w": 257,
      "h": 240,
      "cap": 0,
      "glyph": true
    },
    "uiPrimary": {
      "src": "assets/ui/btn-uiPrimary.webp",
      "w": 405,
      "h": 147,
      "cap": 82
    },
    "uiNav": {
      "src": "assets/ui/btn-uiNav.webp",
      "w": 404,
      "h": 148,
      "cap": 83
    },
    "uiSecondary": {
      "src": "assets/ui/btn-uiSecondary.webp",
      "w": 404,
      "h": 148,
      "cap": 83
    },
    "uiSuccess": {
      "src": "assets/ui/btn-uiSuccess.webp",
      "w": 404,
      "h": 148,
      "cap": 83
    },
    "uiDanger": {
      "src": "assets/ui/btn-uiDanger.webp",
      "w": 401,
      "h": 149,
      "cap": 83
    },
    "uiDisabled": {
      "src": "assets/ui/btn-uiDisabled.webp",
      "w": 403,
      "h": 148,
      "cap": 83
    }
  };
  global.ButtonFrame = F;
  if (typeof module !== 'undefined' && module.exports) module.exports = F;
})(typeof window !== 'undefined' ? window : this);
