/*!
 * button-frame.js — GENERATED by tools/build-buttons.js. Do not edit.
 *
 * The buttons cut from assets/ui/newbuttons.png, and where each one's round end finishes.
 * `cap` is that width in the image's own pixels: draw the left cap at its
 * true proportions, the right cap at its true proportions, and stretch the
 * sliver between them to whatever width the button needs. Stretching the
 * whole picture instead turns the round ends into ovals.
 */
(function (global) {
  'use strict';
  var F = {
    "sun": {
      "src": "assets/ui/btn-sun.webp",
      "w": 336,
      "h": 156,
      "cap": 87
    },
    "tangerine": {
      "src": "assets/ui/btn-tangerine.webp",
      "w": 338,
      "h": 157,
      "cap": 88
    },
    "correct": {
      "src": "assets/ui/btn-correct.webp",
      "w": 339,
      "h": 157,
      "cap": 88
    },
    "wrong": {
      "src": "assets/ui/btn-wrong.webp",
      "w": 336,
      "h": 156,
      "cap": 87
    }
  };
  global.ButtonFrame = F;
  if (typeof module !== 'undefined' && module.exports) module.exports = F;
})(typeof window !== 'undefined' ? window : this);
