/*!
 * button-frame.js — GENERATED by tools/build-buttons.js. Do not edit.
 *
 * The buttons cut from assets/ui/btn.png and assets/ui/numberbutton1.png, and where each one's round end finishes.
 * `cap` is that width in the image's own pixels: draw the left cap at its
 * true proportions, the right cap at its true proportions, and stretch the
 * sliver between them to whatever width the button needs. Stretching the
 * whole picture instead turns the round ends into ovals.
 */
(function (global) {
  'use strict';
  var F = {
    "sun": {
      "src": "assets/ui/btn-sun.webp",
      "w": 285,
      "h": 130,
      "cap": 73
    },
    "tangerine": {
      "src": "assets/ui/btn-tangerine.webp",
      "w": 291,
      "h": 130,
      "cap": 73
    },
    "correct": {
      "src": "assets/ui/btn-correct.webp",
      "w": 283,
      "h": 129,
      "cap": 72
    },
    "wrong": {
      "src": "assets/ui/btn-wrong.webp",
      "w": 285,
      "h": 129,
      "cap": 72
    },
    "convex": {
      "src": "assets/ui/btn-convex.webp",
      "w": 289,
      "h": 131,
      "cap": 73
    },
    "concave": {
      "src": "assets/ui/btn-concave.webp",
      "w": 284,
      "h": 130,
      "cap": 73
    },
    "regular": {
      "src": "assets/ui/btn-regular.webp",
      "w": 285,
      "h": 131,
      "cap": 73
    },
    "irregular": {
      "src": "assets/ui/btn-irregular.webp",
      "w": 286,
      "h": 130,
      "cap": 73
    },
    "sky": {
      "src": "assets/ui/btn-sky.webp",
      "w": 286,
      "h": 130,
      "cap": 73
    },
    "plum": {
      "src": "assets/ui/btn-plum.webp",
      "w": 286,
      "h": 130,
      "cap": 73
    },
    "stepMinus": {
      "src": "assets/ui/btn-stepMinus.webp",
      "w": 167,
      "h": 162,
      "cap": 0,
      "glyph": true
    },
    "stepPlus": {
      "src": "assets/ui/btn-stepPlus.webp",
      "w": 168,
      "h": 164,
      "cap": 0,
      "glyph": true
    }
  };
  global.ButtonFrame = F;
  if (typeof module !== 'undefined' && module.exports) module.exports = F;
})(typeof window !== 'undefined' ? window : this);
