/*!
 * card-frame.js — GENERATED by tools/build-card.js. Do not edit.
 *
 * The option card artwork, and where its glass is.
 *
 * `pane` is the clear area INSIDE the frozen rim, as a fraction of the
 * card, so a shape can be placed in the glass at any size the card is drawn
 * at. Measured from the artwork rather than eyeballed, because the rim is
 * not the same thickness on every edge and a shape centred on the card is
 * not centred in the pane.
 */
(function (global) {
  'use strict';
  var F = {
    src: 'assets/ui/card.webp',
    w: 512,
    h: 472,
    pane: {"x":0.0697,"y":0.0929,"w":0.858,"h":0.8015}
  };
  global.CardFrame = F;
  if (typeof module !== 'undefined' && module.exports) module.exports = F;
})(typeof window !== 'undefined' ? window : this);
