/*!
 * card-frame.js — GENERATED by tools/build-card.js. Do not edit.
 *
 * The two cards, and where each one's face is.
 *
 *   option  the block of ice something TOUCHABLE sits in
 *   panel   the slab a single shape is DISPLAYED on, with nothing to do
 *
 * `pane` is the clear area inside the rim, as a fraction of the card, so a
 * shape can be placed in it at any size the card is drawn at. Measured from
 * the artwork rather than eyeballed, because the rim is not the same
 * thickness on every edge and a shape centred on the card is not centred in
 * the pane.
 */
(function (global) {
  'use strict';
  var F = {
    "option": {
      "src": "assets/ui/card.webp",
      "w": 512,
      "h": 472,
      "pane": {
        "x": 0.0697,
        "y": 0.0929,
        "w": 0.858,
        "h": 0.827
      }
    },
    "panel": {
      "src": "assets/ui/bigcard.webp",
      "w": 1024,
      "h": 834,
      "pane": {
        "x": 0.0254,
        "y": 0.0385,
        "w": 0.9619,
        "h": 0.8048
      }
    },
    "regular": {
      "src": "assets/ui/zone-regular.webp",
      "w": 640,
      "h": 727,
      "pane": {
        "x": 0.0523,
        "y": 0.2538,
        "w": 0.8955,
        "h": 0.6186
      }
    },
    "irregular": {
      "src": "assets/ui/zone-irregular.webp",
      "w": 640,
      "h": 691,
      "pane": {
        "x": 0.0604,
        "y": 0.2518,
        "w": 0.8782,
        "h": 0.676
      }
    }
  };
  global.CardFrame = F;
  if (typeof module !== 'undefined' && module.exports) module.exports = F;
})(typeof window !== 'undefined' ? window : this);
