/*!
 * card-frame.js — GENERATED by tools/build-card.js. Do not edit.
 *
 * The two cards, and where each one's face is.
 *
 *   option  the block of ice something TOUCHABLE sits in
 *   panel   the slab a single shape is DISPLAYED on, with nothing to do
 *
 * `pane` is the clear area inside the rim, as a fraction of the card, so a
 * (panel.pane.h is hand-set to 0.85 after every rebuild: the detector stops at
 * the inner highlight, a tenth short of the glass; keep it.)
 * shape can be placed in it at any size the card is drawn at. Measured from
 * the artwork rather than eyeballed, because the rim is not the same
 * thickness on every edge and a shape centred on the card is not centred in
 * the pane.
 */
(function (global) {
  'use strict';
  var F = {
    "option": {
      "src": "assets/ui/card.webp",
      "w": 512,
      "h": 472,
      "pane": {
        "x": 0.0697,
        "y": 0.0929,
        "w": 0.858,
        "h": 0.827
      }
    },
    "panel": {
      "src": "assets/ui/bigcard.webp",
      "w": 1024,
      "h": 0.85,
      "pane": {
        "x": 0.0414,
        "y": 0.0821,
        "w": 0.918,
        "h": 0.7443
      }
    },
    "plank": {
      "src": "assets/ui/plank.webp",
      "w": 1400,
      "h": 353,
      "pane": {
        "x": 0.0321,
        "y": 0.2206,
        "w": 0.9349,
        "h": 0.6785
      }
    },
    "regular": {
      "src": "assets/ui/zone-regular.webp",
      "w": 640,
      "h": 599,
      "pane": {
        "x": 0.0309,
        "y": 0.0642,
        "w": 0.9391,
        "h": 0.8515
      }
    },
    "irregular": {
      "src": "assets/ui/zone-irregular.webp",
      "w": 640,
      "h": 589,
      "pane": {
        "x": 0.0588,
        "y": 0.0764,
        "w": 0.8825,
        "h": 0.8282
      }
    }
  };
  global.CardFrame = F;
  if (typeof module !== 'undefined' && module.exports) module.exports = F;
})(typeof window !== 'undefined' ? window : this);
