/*!
 * hand-art.js — GENERATED by tools/build-hand.js. Do not edit.
 *
 * The pointing hand the hints use. `tip` is the fingertip, as a fraction of
 * the image: the point that touches what the hand is showing.
 */
(function (global) {
  'use strict';
  var A = {
    "src": "assets/ui/hand.webp",
    "w": 200,
    "h": 240,
    "tip": {
      "x": 0.1353,
      "y": 0.055
    }
  };
  global.HandArt = A;
  if (typeof module !== 'undefined' && module.exports) module.exports = A;
})(typeof window !== 'undefined' ? window : this);
