/*!
 * sleigh-frames.js — GENERATED by tools/build-sleigh-frames.js. Do not edit.
 *
 * The three intro sheets measured from their alpha: every frame's source
 * rectangle, its ground line, and the separate islands inside it.
 *
 * `norm` is the per-sheet scale correction. The three sheets were drawn at
 * three different sizes — the same reindeer measures 314px on the ride
 * sheet, 263 on the dismount and 195 on the departure — and without this the
 * character would change size twice during a single continuous animation.
 */
(function (global) {
  'use strict';
  var F = {
 "base": "assets/swiftee/intro/",
 "norm": {
  "ride": 1,
  "dismount": 1.1939,
  "departure": 1.6103
 },
 "sheets": {
  "ride": {
   "w": 1774,
   "h": 887,
   "frames": [
    {
     "sx": 23,
     "sy": 74,
     "sw": 412,
     "sh": 314,
     "ground": 388,
     "islands": [
      {
       "x": 23,
       "y": 74,
       "w": 412,
       "h": 314
      }
     ]
    },
    {
     "sx": 466,
     "sy": 78,
     "sw": 413,
     "sh": 310,
     "ground": 388,
     "islands": [
      {
       "x": 466,
       "y": 78,
       "w": 413,
       "h": 310
      }
     ]
    },
    {
     "sx": 910,
     "sy": 75,
     "sw": 412,
     "sh": 311,
     "ground": 386,
     "islands": [
      {
       "x": 910,
       "y": 75,
       "w": 412,
       "h": 311
      }
     ]
    },
    {
     "sx": 1353,
     "sy": 74,
     "sw": 410,
     "sh": 314,
     "ground": 388,
     "islands": [
      {
       "x": 1353,
       "y": 74,
       "w": 410,
       "h": 314
      }
     ]
    },
    {
     "sx": 24,
     "sy": 503,
     "sw": 412,
     "sh": 315,
     "ground": 818,
     "islands": [
      {
       "x": 24,
       "y": 503,
       "w": 412,
       "h": 315
      }
     ]
    },
    {
     "sx": 466,
     "sy": 504,
     "sw": 413,
     "sh": 315,
     "ground": 819,
     "islands": [
      {
       "x": 466,
       "y": 504,
       "w": 413,
       "h": 315
      }
     ]
    },
    {
     "sx": 910,
     "sy": 503,
     "sw": 412,
     "sh": 315,
     "ground": 818,
     "islands": [
      {
       "x": 910,
       "y": 503,
       "w": 412,
       "h": 315
      }
     ]
    },
    {
     "sx": 1353,
     "sy": 503,
     "sw": 411,
     "sh": 316,
     "ground": 819,
     "islands": [
      {
       "x": 1353,
       "y": 503,
       "w": 411,
       "h": 316
      }
     ]
    }
   ],
   "file": "assets/swiftee/intro/sheet1.png"
  },
  "dismount": {
   "w": 1983,
   "h": 793,
   "frames": [
    {
     "sx": 29,
     "sy": 112,
     "sw": 348,
     "sh": 263,
     "ground": 375,
     "islands": [
      {
       "x": 29,
       "y": 112,
       "w": 348,
       "h": 263
      }
     ]
    },
    {
     "sx": 440,
     "sy": 113,
     "sw": 351,
     "sh": 262,
     "ground": 375,
     "islands": [
      {
       "x": 440,
       "y": 113,
       "w": 351,
       "h": 262
      }
     ]
    },
    {
     "sx": 844,
     "sy": 113,
     "sw": 346,
     "sh": 262,
     "ground": 375,
     "islands": [
      {
       "x": 844,
       "y": 113,
       "w": 320,
       "h": 262
      }
     ]
    },
    {
     "sx": 1190,
     "sy": 101,
     "sw": 358,
     "sh": 283,
     "ground": 384,
     "islands": [
      {
       "x": 1190,
       "y": 181,
       "w": 177,
       "h": 203
      },
      {
       "x": 1372,
       "y": 169,
       "w": 38,
       "h": 38
      },
      {
       "x": 1420,
       "y": 101,
       "w": 128,
       "h": 142
      }
     ]
    },
    {
     "sx": 1587,
     "sy": 58,
     "sw": 365,
     "sh": 326,
     "ground": 384,
     "islands": [
      {
       "x": 1587,
       "y": 180,
       "w": 179,
       "h": 204
      },
      {
       "x": 1782,
       "y": 168,
       "w": 30,
       "h": 31
      },
      {
       "x": 1817,
       "y": 58,
       "w": 135,
       "h": 149
      }
     ]
    },
    {
     "sx": 150,
     "sy": 501,
     "sw": 191,
     "sh": 168,
     "ground": 669,
     "islands": [
      {
       "x": 150,
       "y": 501,
       "w": 191,
       "h": 168
      }
     ]
    },
    {
     "sx": 513,
     "sy": 517,
     "sw": 193,
     "sh": 191,
     "ground": 708,
     "islands": [
      {
       "x": 513,
       "y": 517,
       "w": 193,
       "h": 191
      }
     ]
    },
    {
     "sx": 860,
     "sy": 531,
     "sw": 211,
     "sh": 180,
     "ground": 711,
     "islands": [
      {
       "x": 860,
       "y": 531,
       "w": 211,
       "h": 180
      }
     ]
    },
    {
     "sx": 1267,
     "sy": 499,
     "sw": 209,
     "sh": 214,
     "ground": 713,
     "islands": [
      {
       "x": 1267,
       "y": 499,
       "w": 209,
       "h": 214
      }
     ]
    },
    {
     "sx": 1657,
     "sy": 499,
     "sw": 209,
     "sh": 214,
     "ground": 713,
     "islands": [
      {
       "x": 1657,
       "y": 499,
       "w": 209,
       "h": 214
      }
     ]
    }
   ],
   "file": "assets/swiftee/intro/sheet2.png"
  },
  "departure": {
   "w": 1774,
   "h": 887,
   "frames": [
    {
     "sx": 25,
     "sy": 175,
     "sw": 414,
     "sh": 204,
     "ground": 379,
     "islands": [
      {
       "x": 25,
       "y": 217,
       "w": 149,
       "h": 162
      },
      {
       "x": 183,
       "y": 175,
       "w": 256,
       "h": 195
      }
     ]
    },
    {
     "sx": 468,
     "sy": 177,
     "sw": 416,
     "sh": 201,
     "ground": 378,
     "islands": [
      {
       "x": 468,
       "y": 216,
       "w": 148,
       "h": 162
      },
      {
       "x": 630,
       "y": 177,
       "w": 254,
       "h": 195
      }
     ]
    },
    {
     "sx": 911,
     "sy": 176,
     "sw": 417,
     "sh": 202,
     "ground": 378,
     "islands": [
      {
       "x": 911,
       "y": 217,
       "w": 149,
       "h": 161
      },
      {
       "x": 1072,
       "y": 176,
       "w": 256,
       "h": 194
      }
     ]
    },
    {
     "sx": 1355,
     "sy": 177,
     "sw": 418,
     "sh": 201,
     "ground": 378,
     "islands": [
      {
       "x": 1355,
       "y": 216,
       "w": 148,
       "h": 162
      },
      {
       "x": 1518,
       "y": 177,
       "w": 255,
       "h": 195
      }
     ]
    },
    {
     "sx": 25,
     "sy": 584,
     "sw": 419,
     "sh": 201,
     "ground": 785,
     "islands": [
      {
       "x": 25,
       "y": 623,
       "w": 149,
       "h": 162
      },
      {
       "x": 213,
       "y": 584,
       "w": 231,
       "h": 192
      }
     ]
    },
    {
     "sx": 468,
     "sy": 623,
     "sw": 419,
     "sh": 162,
     "ground": 785,
     "islands": [
      {
       "x": 468,
       "y": 623,
       "w": 148,
       "h": 162
      },
      {
       "x": 709,
       "y": 671,
       "w": 178,
       "h": 105
      }
     ]
    },
    {
     "sx": 911,
     "sy": 623,
     "sw": 420,
     "sh": 162,
     "ground": 785,
     "islands": [
      {
       "x": 911,
       "y": 623,
       "w": 149,
       "h": 162
      },
      {
       "x": 1236,
       "y": 696,
       "w": 95,
       "h": 80
      }
     ]
    },
    {
     "sx": 1355,
     "sy": 623,
     "sw": 148,
     "sh": 162,
     "ground": 785,
     "islands": [
      {
       "x": 1355,
       "y": 623,
       "w": 148,
       "h": 162
      }
     ]
    }
   ],
   "file": "assets/swiftee/intro/sheet3.png"
  }
 }
};
  global.SleighFrames = F;
  if (typeof module !== 'undefined' && module.exports) module.exports = F;
})(typeof window !== 'undefined' ? window : this);
