#!/usr/bin/env node
/*!
 * build-preload.js — what the loading bar fetches before Start, and how heavy each file is.
 *
 *   node tools/build-preload.js           writes src/core/preload-list.js
 *   node tools/build-preload.js --check   fails if that file is out of date, or names a missing file
 *
 * THE LIST IS READ FROM THE CODE. Every asset the page and the scripts name as a literal —
 * "assets/ui/card.webp?v=bcc5169a" in a frame table, url("assets/bg/ice-vista.webp") in the
 * stylesheet, the story's paintings, the sleigh and measuring sheets — exactly as written,
 * ?v= and all, because the bar only helps if it fetches the very URL the game will ask for
 * (a different query string is a different cache entry, and the warm-up silently misses).
 * Three sets are not literals and are added when the page runs (src/game/game.js
 * startLoading): Swiftee's sheets at the resolution this screen draws him, the voice clips
 * in the format this browser plays, and the fonts.
 *
 * THE SIZES ARE THE FILES' OWN, on disk, so the bar weighs a 900 KB sheet as nine times a
 * 100 KB one from its first frame; a Content-Length that says otherwise corrects it.
 *
 * AND THE AVIF TWINS (tools/build-avif.js): every .webp with an .avif beside it, mapped to
 * the twin's address with its own ?v= (a hash of its bytes, like the frame tables' hashes),
 * which is what Preload.pick() asks for where the browser shows AVIF.
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'src', 'core', 'preload-list.js');
const CHECK = process.argv.includes('--check');

function walk(dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p)); else out.push(p);
  }
  return out;
}
const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/');

// every file the site serves under assets/ (assets/source is the masters, never deployed — nor are
// the Hindi recordings, assets/vo-part-1-hindi/*.opus, which tools/build-vo-hindi.js cuts into assets/vo/hi)
const sizes = {};
walk(path.join(ROOT, 'assets')).map(rel).filter((f) => !/^assets\/source\//.test(f) && !/\.(wav|opus)$/i.test(f) && !/(^|\/)\.[^/]+$/.test(f)).sort()
  .forEach((f) => { sizes[f] = fs.statSync(path.join(ROOT, f)).size; });

// every literal asset URL in the scripts and the page, quoted or inside url(...)
const sources = [path.join(ROOT, 'index.html')].concat(walk(path.join(ROOT, 'src')).filter((f) => /\.js$/.test(f) && f !== OUT));
const RE = /["'(](assets\/[A-Za-z0-9_\-./@]+\.(?:webp|png|jpg|svg))(\?v=[0-9a-f]+)?(?=["')])/g;
const urls = new Set(), missing = [];
sources.forEach((f) => {
  const src = fs.readFileSync(f, 'utf8');
  let m;
  while ((m = RE.exec(src))) {
    const file = m[1];
    if (/^assets\/(source|vo)\//.test(file)) continue;             // the masters; the voice is added at run time
    if (/^assets\/swiftee\/spritesheets\//.test(file)) continue;    // added at run time, at the resolution drawn
    if (!(file in sizes)) { missing.push(file + '  (' + rel(f) + ')'); continue; }
    urls.add(file + (m[2] || ''));
  }
});

// every .webp with an AVIF twin beside it -> the twin's address
const avif = {};
Object.keys(sizes).filter((f) => /\.avif$/.test(f)).forEach((f) => {
  const webp = f.replace(/\.avif$/, '.webp');
  if (!(webp in sizes)) return;
  avif[webp] = f + '?v=' + crypto.createHash('md5').update(fs.readFileSync(path.join(ROOT, f))).digest('hex').slice(0, 8);
});

const text = '/* generated by tools/build-preload.js from the code and the files on disk — do not edit by hand */\n' +
  'window.PreloadList = ' + JSON.stringify({ urls: [...urls].sort(), sizes: sizes, avif: avif }, null, 1) + ';\n';

if (missing.length) {
  console.error('named in the code but not on disk:\n  ' + missing.join('\n  '));
  if (CHECK) process.exit(1);
}
if (CHECK) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have !== text) { console.error('src/core/preload-list.js is OUT OF DATE — run: node tools/build-preload.js'); process.exit(1); }
  console.log('src/core/preload-list.js is up to date: ' + urls.size + ' literal urls, ' + Object.keys(sizes).length + ' sizes');
} else {
  fs.writeFileSync(OUT, text);
  const bytes = [...urls].reduce((a, u) => a + (sizes[u.split('?')[0]] || 0), 0);
  console.log('src/core/preload-list.js: ' + urls.size + ' literal urls (' + (bytes / 1024).toFixed(0) + ' KB), ' + Object.keys(sizes).length + ' file sizes');
}
