#!/usr/bin/env node
/*!
 * build-locales.js — the game's words in every language, where both halves can read them.
 *
 *   node tools/build-locales.js           writes the four files below
 *   node tools/build-locales.js --check   fails if any of them is out of date
 *
 * THE SOURCE IS ONE FILE: polygon-locales.json at the repository's root (English, Hindi,
 * Marathi, Telugu, Gujarati, Odia — the same keys in each). A page cannot fetch a JSON file
 * when it is opened straight off the disk, and the words have to be in hand before the first
 * line is drawn, so the file is copied into a classic script that sets window.POLYGON_LOCALES:
 *
 *   part1-swiftee-lesson/src/core/locales.js      the lesson's copy
 *   part2-frozen-rush/game/js/locales.js          Frozen Rush's copy
 *
 * and the code that reads it (src/core/i18n.js, the lesson's) is copied beside Frozen Rush's,
 * so the two halves choose the language — ?lan= — by the same rules:
 *
 *   part2-frozen-rush/game/js/i18n.js
 *
 * Edit the JSON or the lesson's i18n.js, then run this. tests/i18n.test.js fails while any
 * copy disagrees with its source.
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const LESSON = path.resolve(__dirname, '..');
const REPO = path.resolve(LESSON, '..');
// polygon-locales.json: beside the lesson when it is a repository of its own, at the combined
// repository's root otherwise (POLYGON-PART-1, where Frozen Rush gets its copies too)
const SRC = [path.join(LESSON, 'polygon-locales.json'), path.join(REPO, 'polygon-locales.json')].find((f) => fs.existsSync(f)) || path.join(REPO, 'polygon-locales.json');
const P2JS = path.join(REPO, 'part2-frozen-rush', 'game', 'js');
const CORE = path.join(LESSON, 'src', 'core', 'i18n.js');
const CHECK = process.argv.includes('--check');

function localesScript(data) {
  const keys = Object.keys(data);
  const body = keys.map((k) => '  ' + JSON.stringify(k) + ': ' + JSON.stringify(data[k])).join(',\n');
  return '/* generated by part1-swiftee-lesson/tools/build-locales.js from polygon-locales.json — do not edit by hand */\n' +
    '(function (g) {\n' +
    'g.POLYGON_LOCALES = {\n' + body + '\n};\n' +
    '})(typeof window !== \'undefined\' ? window : this);\n';
}

function outputs() {
  const data = JSON.parse(fs.readFileSync(SRC, 'utf8'));
  const script = localesScript(data);
  const core = fs.readFileSync(CORE, 'utf8');
  const copy = '/* A COPY of part1-swiftee-lesson/src/core/i18n.js, written by part1-swiftee-lesson/tools/build-locales.js —\n' +
    '   edit that one and run the tool; the two halves of the game read ?lan= by the same rules. */\n' + core;
  const out = [[path.join(LESSON, 'src', 'core', 'locales.js'), script]];
  if (fs.existsSync(P2JS)) out.push([path.join(P2JS, 'locales.js'), script], [path.join(P2JS, 'i18n.js'), copy]);
  return out;
}

if (require.main === module) {
  let stale = 0;
  for (const [file, text] of outputs()) {
    const rel = path.relative(REPO, file);
    const now = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (now === text) { console.log('up to date  ' + rel); continue; }
    if (CHECK) { console.log('OUT OF DATE ' + rel); stale++; continue; }
    fs.writeFileSync(file, text);
    console.log('wrote       ' + rel + '  (' + Buffer.byteLength(text) + ' bytes)');
  }
  if (stale) { console.error(stale + ' file(s) out of date: run node part1-swiftee-lesson/tools/build-locales.js'); process.exit(1); }
}

module.exports = { outputs, SRC };
