#!/usr/bin/env node
/*!
 * build-hand.js — the pointing hand the hints use, from the supplied artwork.
 *
 *   assets/source/image copy.png  (300×360, transparent)  →  assets/ui/hand.webp
 *                                                        src/game/hand-art.js
 *
 * The hand is drawn at about a fingertip's size over the stage, so the file is
 * cropped to the glove's own bounds and written at twice its largest drawn
 * size. The FINGERTIP is measured, not guessed: it is where the hand touches
 * the thing it points at, so the hint puts that pixel — not the corner of the
 * image — on the target. Run once after replacing the source:
 *   node tools/build-hand.js
 */
'use strict';
const fs = require('node:fs'), path = require('node:path'), http = require('node:http'), crypto = require('node:crypto');
const { chromium } = require('playwright');
const ROOT = path.resolve(__dirname, '..');
const SRC = 'assets/source/image copy.png', OUT = 'assets/ui/hand.webp', ART = 'src/game/hand-art.js', HEIGHT = 240;
function serve() { const srv = http.createServer((q, r) => { const f = path.join(ROOT, decodeURIComponent(q.url.split('?')[0])); if (!fs.existsSync(f)) { r.writeHead(404); return r.end(); } r.writeHead(200, { 'Content-Type': 'image/png', 'Access-Control-Allow-Origin': '*' }); fs.createReadStream(f).pipe(r); }); return new Promise((res) => srv.listen(0, () => res(srv))); }
(async () => {
  const srv = await serve(); const port = srv.address().port;
  const b = await chromium.launch({ channel: 'chrome' });
  const pg = await b.newPage();
  await pg.setContent('<canvas id="c"></canvas>');
  const out = await pg.evaluate(async ({ url, height }) => {
    const img = new Image(); img.crossOrigin = 'anonymous'; img.src = url; await img.decode();
    const c0 = document.createElement('canvas'); c0.width = img.width; c0.height = img.height;
    const x0 = c0.getContext('2d'); x0.drawImage(img, 0, 0);
    const d = x0.getImageData(0, 0, c0.width, c0.height).data;
    const A = (x, y) => d[(y * c0.width + x) * 4 + 3];
    let minX = c0.width, maxX = 0, minY = c0.height, maxY = 0;
    for (let y = 0; y < c0.height; y++) for (let x = 0; x < c0.width; x++) if (A(x, y) > 40) { minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y); }
    // the fingertip: the middle of the topmost few rows of glove, then a little
    // into the pad (the point of contact is inside the outline, not on it)
    const band = Math.max(4, Math.round((maxY - minY) * 0.05));
    let sx = 0, n = 0;
    for (let y = minY; y <= minY + band; y++) for (let x = minX; x <= maxX; x++) if (A(x, y) > 40) { sx += x; n++; }
    const tipX = sx / Math.max(1, n), tipY = minY + band * 1.1;
    const pad = 2, cx0 = Math.max(0, minX - pad), cy0 = Math.max(0, minY - pad);
    const cw = Math.min(c0.width, maxX + pad + 1) - cx0, chh = Math.min(c0.height, maxY + pad + 1) - cy0;
    const k = height / chh, W = Math.round(cw * k), H = height;
    const c = document.getElementById('c'); c.width = W; c.height = H;
    const x = c.getContext('2d'); x.imageSmoothingQuality = 'high';
    x.drawImage(img, cx0, cy0, cw, chh, 0, 0, W, H);
    return { w: W, h: H, tip: { x: +((tipX - cx0) / cw).toFixed(4), y: +((tipY - cy0) / chh).toFixed(4) }, webp: c.toDataURL('image/webp', 0.92) };
  }, { url: `http://127.0.0.1:${port}/${encodeURI(SRC)}`, height: HEIGHT });
  const buf = Buffer.from(out.webp.split(',')[1], 'base64');
  fs.writeFileSync(path.join(ROOT, OUT), buf);
  const js = `/*!
 * hand-art.js — GENERATED by tools/build-hand.js. Do not edit.
 *
 * The pointing hand the hints use. \`tip\` is the fingertip, as a fraction of
 * the image: the point that touches what the hand is showing.
 */
(function (global) {
  'use strict';
  var A = ${JSON.stringify({ src: OUT + '?v=' + crypto.createHash('md5').update(buf).digest('hex').slice(0, 8), w: out.w, h: out.h, tip: out.tip }, null, 2).replace(/\n/g, '\n  ')};
  global.HandArt = A;
  if (typeof module !== 'undefined' && module.exports) module.exports = A;
})(typeof window !== 'undefined' ? window : this);
`;
  fs.writeFileSync(path.join(ROOT, ART), js);
  console.log(SRC + ' -> ' + OUT + '  ' + out.w + 'x' + out.h + '  ' + Math.round(buf.length / 1024) + ' KB  tip ' + JSON.stringify(out.tip));
  await b.close(); srv.close();
})().catch((e) => { console.error(e); process.exit(1); });
