#!/usr/bin/env node
/*!
 * make-opus.js — every voice clip's .ogg as Ogg Opus, made from its .mp3 twin.
 *
 *   node tools/make-opus.js            convert every .ogg that is not Opus yet, or is older than its mp3
 *   node tools/make-opus.js --force    convert them all again
 *
 * WHY OPUS. It is the codec built for speech at low bitrates: at 40 kbps mono it is clean,
 * and it is about two thirds the size of the Vorbis q1 clips it replaces. Chrome, Edge,
 * Firefox and Android play Ogg Opus; Safari takes the .mp3 unless it says it can play Opus
 * in Ogg (src/audio/vo.js asks), so the mp3 stays as the one fallback, and only one of the
 * pair is ever downloaded.
 *
 * NEVER BIGGER. A clip is tried at 40, then 32, then 24 kbps (Opus's speech mode), and the
 * first that comes out smaller than the Vorbis file it replaces is kept. One that is smaller
 * at none of them keeps its Vorbis file, which every Opus-capable browser also plays.
 *
 * THE TIMING DOES NOT MOVE. Opus writes its encoder delay into the file and every decoder
 * trims it, so a word's start in the clip is where it was (checked against the mp3 by the
 * envelope: no clip moved by as much as 5 ms). The index's word times, lengths and speech
 * ends are left exactly as they were measured; only each clip's revision is renewed, since
 * that is a hash of its bytes (tools/build-vo-index.js revOf, reproduced here).
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync, spawnSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const VO = path.join(ROOT, 'assets', 'vo');
const FORCE = process.argv.includes('--force');
const LADDER = [40, 32, 24];

const codec = (f) => {
  const r = spawnSync('ffprobe', ['-v', 'error', '-select_streams', 'a:0', '-show_entries', 'stream=codec_name', '-of', 'csv=p=0', f], { encoding: 'utf8' });
  return (r.stdout || '').trim();
};
const opus = (src, out, kb) => execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', '-i', src, '-map', '0:a:0',
  '-c:a', 'libopus', '-b:a', kb + 'k', '-vbr', 'on', '-application', 'voip', '-map_metadata', '-1', out]);

const ids = fs.readdirSync(VO).filter((f) => /\.mp3$/.test(f)).map((f) => f.replace(/\.mp3$/, '')).sort();
let made = 0, kept = 0, refused = [], before = 0, after = 0;
const tmp = path.join(VO, '.make-opus.tmp.ogg');
for (const id of ids) {
  const mp3 = path.join(VO, id + '.mp3'), ogg = path.join(VO, id + '.ogg');
  const had = fs.existsSync(ogg) ? fs.statSync(ogg).size : Infinity;
  const isOpus = fs.existsSync(ogg) && codec(ogg) === 'opus';
  if (isOpus && !FORCE && fs.statSync(ogg).mtimeMs >= fs.statSync(mp3).mtimeMs) { kept++; before += had; after += had; continue; }
  // the bar to clear: smaller than the Vorbis being replaced (a re-made Opus clip need only beat its mp3)
  const bar = isOpus ? fs.statSync(mp3).size : Math.min(had, fs.statSync(mp3).size);
  let got = 0;
  for (const kb of LADDER) {
    opus(mp3, tmp, kb);
    if (fs.statSync(tmp).size < bar) { got = kb; break; }
  }
  if (!got) { refused.push(id); try { fs.unlinkSync(tmp); } catch (e) {} before += had; after += had; continue; }
  before += isFinite(had) ? had : 0;
  fs.renameSync(tmp, ogg);
  after += fs.statSync(ogg).size;
  made++;
}

/* THE REVISIONS, and only those (see above) */
const revOf = (id) => {
  const h = crypto.createHash('md5');
  ['.mp3', '.ogg'].forEach((ext) => { const f = path.join(VO, id + ext); if (fs.existsSync(f)) h.update(fs.readFileSync(f)); });
  return h.digest('hex').slice(0, 8);
};
const IDX = path.join(VO, 'index.json');
const idx = JSON.parse(fs.readFileSync(IDX, 'utf8'));
let renewed = 0;
idx.clips.forEach((id) => { const v = revOf(id); if (idx.rev[id] !== v) { idx.rev[id] = v; renewed++; } });
fs.writeFileSync(IDX, JSON.stringify(idx, null, 2) + '\n');
fs.writeFileSync(path.join(VO, 'index.js'),
  '/* generated by tools/build-vo-index.js from the same data as index.json — read only by a page opened off the disk (src/audio/vo.js) */\n' +
  'window.VO_INDEX = ' + JSON.stringify(idx) + ';\n');

console.log(made + ' made, ' + kept + ' already Opus' + (refused.length ? ', kept as Vorbis (not smaller at any rate): ' + refused.join(' ') : '') +
  ';  ' + (before / 1024).toFixed(0) + ' KB -> ' + (after / 1024).toFixed(0) + ' KB;  ' + renewed + ' revisions renewed');
